security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: plaintext
    providers:
        in_memory_users:
            memory:
                users:
                    - identifier: '%env(API_BASIC_USERNAME)%'
                      password: '%env(API_BASIC_PASSWORD)%'
                      roles: [ ROLE_ADMIN_API ]
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/api/
            http_basic: ~
    access_control:
        - { path: ^/api/, roles: ROLE_ADMIN_API }

